1. В файле находится N натуральных чисел, записанных через пробел.
Среди чисел не хватает одного, чтобы выполнялось условие A[i] - 1 = A[i-1]. Найдите это число.

2. Дан список чисел. Создайте список, в который попадают числа, описываемые возрастающую последовательность.
Порядок элементов менять нельзя.
*Пример:*
[1, 5, 2, 3, 4, 6, 1, 7] => [1, 2, 3] или [1, 7] или [1, 6, 7] и т.д.

3. Напишите программу, удаляющую из текста все слова, содержащие "абв".